name: Automerge Codex PRs on green

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: >
      github.actor == 'github-actions[bot]' || contains(github.event.pull_request.user.login, 'codex')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure Buyers Smoke passes on PR
        run: echo "Use branch protection to require 'Buyers Smoke — animated-cellar (NF p01)'"  # enforced in repo settings

      - name: Merge when required checks pass
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });
            const failing = checks.check_runs.filter(c => c.conclusion && c.conclusion !== 'success');
            if (failing.length === 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash'
              });
            }