name: buyers-autofix

on:
  workflow_run:
    workflows: [ "buyers-smoke" ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for patch/PR)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download buyers-smoke artifact from triggering run
        uses: actions/download-artifact@v4
        with:
          name: buyers-smoke
          # This special input picks artifacts from the triggering workflow_run
          run-id: ${{ github.event.workflow_run.id }}
          path: _smoke

      - name: Show smoke
        run: |
          echo "Contents of _smoke:"
          ls -la _smoke || true
          echo "smoke.json:"
          cat _smoke/smoke.json || true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run fixer (backend/scripts/autofix.mjs)
        env:
          SMOKE_JSON: _smoke/smoke.json
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node backend/scripts/autofix.mjs

      - name: Create PR with changes (if any)
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bot/autofix-${{ github.event.workflow_run.id }}
          title: "Autofix: buyers-smoke ${{ github.event.workflow_run.id }}"
          commit-message: "autofix: buyers-smoke ${{ github.event.workflow_run.id }}"
          body: |
            Automated fixes based on buyers-smoke artifact.
            Trigger run: ${{ github.event.workflow_run.html_url }}
          labels: autofix