name: auto-merge autofix PRs

on:
  pull_request:
    types: [opened, labeled, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: contains(github.event.pull_request.labels.*.name, 'autofix')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge (squash)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          PR="${{ github.event.pull_request.number }}"
          gh pr merge "$PR" --squash --auto --delete-branch
