name: buyers-autofix

on:
  workflow_run:
    workflows: ["buyers-smoke", "buyers-smoke-animated-cellar"]
    types: [completed]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download smoke artifacts (if any)
        uses: actions/download-artifact@v4
        with:
          name: buyers-smoke
          path: artifacts
        continue-on-error: true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend deps
        working-directory: Backend
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --prefer-offline --no-audit --fund=false
          else
            npm i --prefer-offline --no-audit --fund=false
          fi

      - name: Run autofix
        working-directory: Backend
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: node scripts/autofix.mjs
