name: AutoFix Buyers

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Buyers Smoke — animated-cellar (NF p01)"]
    types: [completed]

jobs:
  autofix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      # LLM selection
      LLM_PROVIDER: openrouter
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      LLM_MODEL: anthropic/claude-3.5-sonnet
      # Guardrails
      ALLOW_PATHS: Backend/src,Backend/routes,Backend/devtools
      MAX_PATCH_LINES: 800
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # optional: pull the last smoke json into smoke-output.json if you publish it
      # - name: Download last smoke artifact (optional)
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: buyers-smoke-usca-50
      #     path: .
      # - run: mv buyers-smoke.json smoke-output.json || true

      - name: Run autofix
        run: node scripts/auto-fix.mjs