name: Buyers Smoke — animated-cellar (NF p01)

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: [any, us, usca]
        radius: [2000, 200, 50]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run smoke
        env:
          API: https://p01--animated-cellar--vz4ftkwrzdfs.code.run/api/v1/leads/find-buyers
          # If you don't have a secret yet, this fallback uses the key you've been testing with.
          KEY: ${{ secrets.NF_API_KEY || 'NFjeipPuj44kMS2dfjsyHSkdKSt97S6s5f56sG5' }}
          SUPPLIER: peekpackaging.com
          REGION: ${{ matrix.region }}
          RADIUS_MI: ${{ matrix.radius }}
          OFFER: "custom packaging; corrugated boxes; printed mailers"
          SOLVES: "short lead times; custom printed boxes; ecommerce packaging"
          TITLES: "Purchasing Manager, Procurement Manager, Buyer, Supply Chain Manager"
          VERBOSE: "true"
        run: |
          node Backend/devtools/smoke/find-buyers.mjs \
            | tee "buyers-smoke-${{ matrix.region }}-${{ matrix.radius }}.json"

      - uses: actions/upload-artifact@v4
        with:
          name: buyers-smoke-${{ matrix.region }}-${{ matrix.radius }}
          path: buyers-smoke-${{ matrix.region }}-${{ matrix.radius }}.json
          overwrite: true