name: Buyers Smoke

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "Backend/devtools/smoke/find-buyers.mjs"
      - ".github/workflows/buyers-smoke.yml"

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        supplier: [ peekpackaging.com ]
        region: [ usca, us ]
        radiusMi: [ 50, 200 ]
        include:
          - persona_offer: "packaging supplies"
            persona_solves: "custom boxes, kitting, fulfillment"
            persona_titles: "Procurement Manager, Operations Manager, Warehouse Manager"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run smoke
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          SUPPLIER: ${{ matrix.supplier }}
          REGION: ${{ matrix.region }}
          RADIUS_MI: ${{ matrix.radiusMi }}
          OFFER: ${{ matrix.persona_offer }}
          SOLVES: ${{ matrix.persona_solves }}
          TITLES: ${{ matrix.persona_titles }}
          VERBOSE: 'true'
        run: |
          node Backend/devtools/smoke/find-buyers.mjs | tee "buyers-smoke-${{ matrix.region }}-${{ matrix.radiusMi }}.log"

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: buyers-smoke-logs
          path: buyers-smoke-*.log
