name: buyers-autofix

on:
  workflow_run:
    workflows: ["buyers-smoke"]
    types: [completed]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Download smoke artifacts (if any)
        uses: actions/download-artifact@v4
        with:
          name: buyers-smoke
          path: artifacts
        continue-on-error: true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      # Sanity: print which providers are available (presence only; no secrets).
      - name: Provider env probe
        run: |
          has() { [ -n "$1" ] && echo present || echo missing; }
          echo "GEMINI_API_KEY: $(has "${GEMINI_API_KEY}")"
          echo "HF_API_TOKEN:   $(has "${HF_API_TOKEN}")"
          echo "GROQ_API_KEY:   $(has "${GROQ_API_KEY}")"
          echo "OPENROUTER_API_KEY: $(has "${OPENROUTER_API_KEY}")"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HF_API_TOKEN:   ${{ secrets.HF_API_TOKEN }}
          GROQ_API_KEY:   ${{ secrets.GROQ_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

      - name: Run autofix (free-only; OpenRouter disabled)
        working-directory: Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}

          # Provider order is handled by the script: Gemini -> HF -> Groq -> OpenRouter
          # Pass free providers:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HF_API_TOKEN:   ${{ secrets.HF_API_TOKEN }}
          HF_MODEL:       ${{ secrets.HF_MODEL }}
          GROQ_API_KEY:   ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL:     ${{ secrets.GROQ_MODEL }}

          # Force-disable OpenRouter for now (overrides any repo/org secret).
          OPENROUTER_API_KEY: ""
          OPENROUTER_MODEL:   ""
        run: node scripts/autofix.mjs

      - name: Upload status artifact
        uses: actions/upload-artifact@v4
        with:
          name: autofix-status
          path: autofix-status.json
        continue-on-error: true
