name: buyers-autofix

on:
  workflow_run:
    workflows: ["buyers-smoke"]
    types: [completed]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Download smoke artifacts (if any)
        uses: actions/download-artifact@v4
        with:
          name: buyers-smoke
          path: artifacts
        continue-on-error: true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      # No npm install. Script can repair core files without builds.
      - name: Run autofix
        working-directory: Backend
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
        run: node scripts/autofix.mjs
