name: Buyers Smoke

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "Backend/devtools/smoke/find-buyers.mjs"
      - ".github/workflows/buyers-smoke.yml"
      - "Backend/src/**"

jobs:
  smoke:
    name: smoke (${{ matrix.supplier }}, ${{ matrix.region }}, ${{ matrix.radius }}, expect=${{ matrix.expect }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { supplier: "peekpackaging.com", region: "usca", radius: 50,  expect: 200 }
          - { supplier: "peekpackaging.com", region: "usca", radius: 200, expect: 200 }
          - { supplier: "peekpackaging.com", region: "us",   radius: 50,  expect: 400 }
          - { supplier: "peekpackaging.com", region: "us",   radius: 200, expect: 400 }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run smoke
        id: smoke
        env:
          API_URL: ${{ secrets.BUYERS_API_URL }}   # e.g. https://p01--animated-cellar--...code.run/api/v1/leads/find-buyers
          API_KEY: ${{ secrets.BUYERS_API_KEY }}   # your x-api-key
          SUPPLIER: ${{ matrix.supplier }}
          REGION: ${{ matrix.region }}
          RADIUS_MI: ${{ matrix.radius }}
          VERBOSE: "true"
        run: |
          set -euo pipefail
          mkdir -p .smoke
          node Backend/devtools/smoke/find-buyers.mjs | tee ".smoke/out.json"
          # Optional check: non-zero exit means transport issue
          echo "done"

      - name: Attach result (unique artifact per matrix)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: buyers-smoke-${{ matrix.supplier }}-${{ matrix.region }}-${{ matrix.radius }}-expect${{ matrix.expect }}
          path: .smoke/out.json
          if-no-files-found: warn
          retention-days: 3
