name: Buyers Smoke — animated-cellar (NF p01)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  smoke:
    name: smoke (peekpackaging.com, usca, r=50, expect=200)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      API_URL: https://p01--animated-cellar--vz4ftkwrzdfs.code.run/api/v1/leads/find-buyers
      # Use your working key here if your API enforces it. If not required, leave blank.
      API_KEY: ${{ secrets.NF_API_KEY }}
      REGION: usca
      RADIUS_MI: 50
      SUPPLIER: peekpackaging.com
      VERBOSE: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run smoke
        id: run
        shell: bash
        run: |
          set -euo pipefail
          node Backend/devtools/smoke/find-buyers.mjs \
            | tee smoke-result.json

          # derive a tiny status for downstream (success if status==200)
          STATUS=$(jq -r '.steps.call.status // 0' smoke-result.json || echo 0)
          OK=false
          if [ "$STATUS" = "200" ]; then OK=true; fi

          echo "status=$STATUS" >> "$GITHUB_OUTPUT"
          echo "ok=$OK"       >> "$GITHUB_OUTPUT"

      - name: Upload smoke artifact (unique name per run)
        uses: actions/upload-artifact@v4
        with:
          name: buyers-smoke-animated-cellar-${{ github.run_id }}
          path: smoke-result.json
          if-no-files-found: error
