name: buyers-autofix

on:
  workflow_run:
    workflows: ["buyers-smoke"]
    types: [completed]
  push:
    branches: [ main ]
  schedule:
    - cron: "*/15 * * * *"   # run every 15 minutes
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: buyers-autofix
  cancel-in-progress: true

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Download smoke artifacts (if any)
        uses: actions/download-artifact@v4
        with:
          name: buyers-smoke
          path: artifacts
        continue-on-error: true

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Provider env probe
        run: |
          has() { [ -n "$1" ] && echo present || echo missing; }
          echo "GEMINI_API_KEY: $(has "${GEMINI_API_KEY}")"
          echo "HF_API_TOKEN:   $(has "${HF_API_TOKEN}")"
          echo "GROQ_API_KEY:   $(has "${GROQ_API_KEY}")"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HF_API_TOKEN:   ${{ secrets.HF_API_TOKEN }}
          GROQ_API_KEY:   ${{ secrets.GROQ_API_KEY }}

      - name: Run autofix (Gemini -> HF -> Groq; OpenRouter disabled)
        working-directory: Backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}

          # Providers (order handled by script)
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          HF_API_TOKEN:   ${{ secrets.HF_API_TOKEN }}
          HF_MODEL:       ${{ secrets.HF_MODEL }}
          GROQ_API_KEY:   ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL:     ${{ secrets.GROQ_MODEL }}

          # Debug notes in summary/issue (no GH debug needed)
          DEBUG_AUTOFIX: "1"
        run: node scripts/autofix.mjs

      - name: Upload status artifact
        uses: actions/upload-artifact@v4
        with:
          name: autofix-status
          path: autofix-status.json
        continue-on-error: true
