name: Ingest Scheduler
on:
schedule:
- cron: "*/5 * * * *"
workflow_dispatch:


env:
API_BASE: https://<YOUR-NF-ROUTE>.northflank.app


jobs:
run:
runs-on: ubuntu-latest
steps:
- name: CSE (example)
run: |
curl -fsS --retry 2 -H "x-admin-token: ${{ secrets.ADMIN_TOKEN }}" \
"$API_BASE/api/v1/admin/poll-now?source=cse"
